### PR TITLE
add: CMake Build System

### PR DESCRIPTION
**Pull request by ObiWahn**
Hi,

I have added a basic CMake configuration for your lib. If you are interested I will help you to create full configuration that works well on linux, osx and windows.

With this i am able to use snap like:
- clone snap into my project
- add to CMakeLists.txt:

``` cmake
    add_subdirectory(snap)
    add_executable(myproj src/main.cpp)
    target_link_libraries(myproj snap)
```

### CODE REVIEW

**Comment by swallat** [comment]
Thanks, I needed that, too. +1 cmake support

**Comment by Qix-** [comment]
This would be nice.

**Comment by leezu** [comment]
Any chance of this getting merged?

**Comment by roks** [comment]
Thank you very much for your contribution! We have added significant new code to SNAP recently and there are a few open issues. Everything has been merged to an intermediate repo and a pull request has been created: https://github.com/ObiWahn/snap/pull/1. I propose to move the discussion there and merge your changes after the issues have been resolved.

**Comment by ObiWahn** [comment]
What do i need to do to build snap-adv

**Pull request closed without merging**
